name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Docker image
        run: docker build ./container/ --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/ownvault-server:latest
      - name: Docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/ownvault-server:latest
